### ISSUE TITLE
Are these QRCodes valid?

### ISSUE THREAD

**Issue by lhridley** [jverkoey/ObjQREncoder#3]
I've been scanning the QRCodes generated by this library, and my scanner is not reading them.

It has no problem with the QRCodes generated by Google Charts API

**Comment by gabrielar** [comment]
How do you create the codes. Can you attach somehow a screen shot?

**Comment by lhridley** [comment]
Dude, sorry, but no.  After a month of not hearing anything I found a working QRCode library and deleted yours.  I no longer have the source.
