### ISSUE TITLE
Long strings encoding

### ISSUE THREAD

**Issue by Selirion** [jverkoey/ObjQREncoder#5]
Hello!
Could you explain how use this Encoder correctly with long strings?
I've try something like

  for(int i=4; i<12;i++)
  {
    image = [QREncoder encode:link size:i correctionLevel:QRCorrectionLevelHigh];
    if(image != nil)
    {
      NSLog(@"%d %p",i, image);
      break;
    }
  }
but result can't be decoded by different decoders when i=8, and crash if string a bit longer: 
"Project (720,0xa0597500) malloc: **\* error for object 0x6050004: incorrect checksum for freed object - object was probably modified after being freed." 

I've try to set size=12 for each input, but result can't be decoded too.

**Comment by Selirion** [comment]
OK, it works perfectly with QRCorrectionLevelLow

**Comment by KgwSmile** [comment]
I also have same problem as Selirion.
Now,I 'm going to make QR code about 0 ~ 230 characters.

Could you explain how use this Encoder correctly with strings of different lengths?

[QREncoder encode:strQRContent size:iSize correctionLevel:QRCorrectionLevelHigh];
In other way,please notice to me when I should change size value.

Thanks.
